"""create_sensor_telemetry_and_maintenance_tables

Revision ID: 4e76ed180b6e
Revises: 
Create Date: 2026-09-27 16:12:08.604648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e76ed180b6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_maint_device_time', 'maintenance_events', ['device_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_maintenance_events_device_id'), 'maintenance_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_maintenance_events_id'), 'maintenance_events', ['id'], unique=False)
    op.add_column('sensor_telemetry', sa.Column('ts_shell_temp_c', sa.Float(), nullable=False))
    op.add_column('sensor_telemetry', sa.Column('b_ext_leakage_flux_mt', sa.Float(), nullable=False))
    op.add_column('sensor_telemetry', sa.Column('v_n_neutral_voltage_v', sa.Float(), nullable=False))
    op.add_column('sensor_telemetry', sa.Column('i_n_coil_current_a', sa.Float(), nullable=False))
    op.add_column('sensor_telemetry', sa.Column('delta_pc_cooling_pressure_bar', sa.Float(), nullable=False))
    op.alter_column('sensor_telemetry', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_sensor_telemetry_device_id'), table_name='sensor_telemetry')
    op.drop_index(op.f('ix_sensor_telemetry_timestamp'), table_name='sensor_telemetry')
    op.create_index('ix_sensor_device_timestamp', 'sensor_telemetry', ['device_id', 'timestamp'], unique=False)
    op.drop_column('sensor_telemetry', 'current_amps')
    op.drop_column('sensor_telemetry', 'temperature_c')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_telemetry', sa.Column('temperature_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('sensor_telemetry', sa.Column('current_amps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index('ix_sensor_device_timestamp', table_name='sensor_telemetry')
    op.create_index(op.f('ix_sensor_telemetry_timestamp'), 'sensor_telemetry', ['timestamp'], unique=False)
    op.create_index(op.f('ix_sensor_telemetry_device_id'), 'sensor_telemetry', ['device_id'], unique=False)
    op.alter_column('sensor_telemetry', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('sensor_telemetry', 'delta_pc_cooling_pressure_bar')
    op.drop_column('sensor_telemetry', 'i_n_coil_current_a')
    op.drop_column('sensor_telemetry', 'v_n_neutral_voltage_v')
    op.drop_column('sensor_telemetry', 'b_ext_leakage_flux_mt')
    op.drop_column('sensor_telemetry', 'ts_shell_temp_c')
    op.drop_index(op.f('ix_maintenance_events_id'), table_name='maintenance_events')
    op.drop_index(op.f('ix_maintenance_events_device_id'), table_name='maintenance_events')
    op.drop_index('ix_maint_device_time', table_name='maintenance_events')
    op.drop_table('maintenance_events')
    # ### end Alembic commands ###
